version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: desafio2_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: persisted_db
    ports:
      - "5432:5432"
    volumes:
      # Volume nomeado para persistir os dados do PostgreSQL
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
